### ISSUE TITLE
Install causes CP bundling to fail

### ISSUE THREAD

**Issue by tom-m-clarity-growth** [lucky-media/seochecker-statamic#23]
In addition, the install fails as there is something not setup correctly as it breaks the CP. Locally, I had to go into the vendor folder and run `npm i && npm run dev` to get it to work locally. This needs sorting so that we can install seamlessly with confidence it won't cause issues on the production version of our client's site.

Can anyone fix this as I can't justify purchasing the licence if it's not working properly.

P.S The Statamic Marketplace listing shows `composer require lucky-media/seochecker-statamic` as the install command but then further down in the description the correct install is listed as `composer require lucky-media/seopulse-statamic`. This needs updating.

**Comment by Afan417** [comment]
Hey @tom-m-clarity-growth! 

Thanks for that. We've updated the command on the Statamic page.

We were also able to fix the issue you experienced. Can you try again and confirm that it works for you too?

**Comment by tom-m-clarity-growth** [comment]
All good now, thanks for the quick response!
